-- Structural VHDL generated by gnetlist
-- Context clause
library IEEE;
use IEEE.Std_Logic_1164.all;
-- Entity declaration

ENTITY not found IS
END not found;


-- Secondary unit
ARCHITECTURE netlist OF not found IS
    COMPONENT FBBC
    END COMPONENT ;

    SIGNAL A11 : Std_Logic;
    SIGNAL A10 : Std_Logic;
    SIGNAL A09 : Std_Logic;
    SIGNAL A08 : Std_Logic;
    SIGNAL A07 : Std_Logic;
    SIGNAL A06 : Std_Logic;
    SIGNAL A05 : Std_Logic;
    SIGNAL A04 : Std_Logic;
    SIGNAL A03 : Std_Logic;
    SIGNAL A02 : Std_Logic;
    SIGNAL A01 : Std_Logic;
    SIGNAL A00 : Std_Logic;
    SIGNAL AC_CLK : Std_Logic;
    SIGNAL AC_CLEAR : Std_Logic;
BEGIN
-- Architecture statement part
    FB203 : FBBC
    PORT MAP (
        1 => AC_CLEAR,
        2 => AC_CLK,
        3 => A07,
        4 => A08,
        5 => A09,
        6 => A10,
        7 => A11);

    FB202 : FBBC
    PORT MAP (
        1 => AC_CLEAR,
        2 => AC_CLK,
        3 => A03,
        4 => A04,
        5 => A05,
        6 => A06,
        7 => A07);

    FB201 : FBBC
    PORT MAP (
        1 => AC_CLEAR,
        2 => AC_CLK,
        3 => AC_CLK,
        4 => A00,
        5 => A01,
        6 => A02,
        7 => A03);

-- Signal assignment part
END netlist;
