-- Structural VHDL generated by gnetlist
-- Context clause
library IEEE;
use IEEE.Std_Logic_1164.all;
-- Entity declaration

ENTITY not found IS
END not found;


-- Secondary unit
ARCHITECTURE netlist OF not found IS
    COMPONENT G_OUTPUT
    END COMPONENT ;

    COMPONENT G_INPUT
    END COMPONENT ;

    COMPONENT G_JKC
    END COMPONENT ;

    COMPONENT G_CLKBUF
    END COMPONENT ;

    COMPONENT G_INV
    END COMPONENT ;

    COMPONENT TIMEBASE
    END COMPONENT ;

    COMPONENT ADDRESSCOUNTER
    END COMPONENT ;

    COMPONENT G_2AND
    END COMPONENT ;

    SIGNAL A06 : Std_Logic;
    SIGNAL A07 : Std_Logic;
    SIGNAL A08 : Std_Logic;
    SIGNAL A09 : Std_Logic;
    SIGNAL A10 : Std_Logic;
    SIGNAL A11 : Std_Logic;
    SIGNAL A00 : Std_Logic;
    SIGNAL A01 : Std_Logic;
    SIGNAL A02 : Std_Logic;
    SIGNAL A03 : Std_Logic;
    SIGNAL A04 : Std_Logic;
    SIGNAL A05 : Std_Logic;
    SIGNAL unnamed_net37 : Std_Logic;
    SIGNAL unnamed_net36 : Std_Logic;
    SIGNAL unnamed_net35 : Std_Logic;
    SIGNAL unnamed_net34 : Std_Logic;
    SIGNAL unnamed_net33 : Std_Logic;
    SIGNAL unnamed_net32 : Std_Logic;
    SIGNAL unnamed_net31 : Std_Logic;
    SIGNAL unnamed_net30 : Std_Logic;
    SIGNAL unnamed_net29 : Std_Logic;
    SIGNAL unnamed_net28 : Std_Logic;
    SIGNAL unnamed_net27 : Std_Logic;
    SIGNAL TB_100us : Std_Logic;
    SIGNAL unnamed_net26 : Std_Logic;
    SIGNAL TB_200us : Std_Logic;
    SIGNAL unnamed_net25 : Std_Logic;
    SIGNAL TB_500us : Std_Logic;
    SIGNAL unnamed_net24 : Std_Logic;
    SIGNAL TB_1ms : Std_Logic;
    SIGNAL unnamed_net23 : Std_Logic;
    SIGNAL TB_2ms : Std_Logic;
    SIGNAL unnamed_net22 : Std_Logic;
    SIGNAL TB_5ms : Std_Logic;
    SIGNAL unnamed_net21 : Std_Logic;
    SIGNAL TB_1us : Std_Logic;
    SIGNAL unnamed_net20 : Std_Logic;
    SIGNAL TB_2us : Std_Logic;
    SIGNAL unnamed_net19 : Std_Logic;
    SIGNAL TB_5us : Std_Logic;
    SIGNAL unnamed_net18 : Std_Logic;
    SIGNAL TB_10us : Std_Logic;
    SIGNAL unnamed_net17 : Std_Logic;
    SIGNAL TB_20us : Std_Logic;
    SIGNAL unnamed_net16 : Std_Logic;
    SIGNAL TB_50us : Std_Logic;
    SIGNAL unnamed_net15 : Std_Logic;
    SIGNAL unnamed_net14 : Std_Logic;
    SIGNAL CLK : Std_Logic;
    SIGNAL unnamed_net13 : Std_Logic;
    SIGNAL GND : Std_Logic;
    SIGNAL unnamed_net12 : Std_Logic;
    SIGNAL unnamed_net11 : Std_Logic;
    SIGNAL unnamed_net10 : Std_Logic;
    SIGNAL VCC : Std_Logic;
    SIGNAL unnamed_net9 : Std_Logic;
    SIGNAL S1 : Std_Logic;
    SIGNAL unnamed_net8 : Std_Logic;
    SIGNAL R3 : Std_Logic;
    SIGNAL unnamed_net7 : Std_Logic;
    SIGNAL R2 : Std_Logic;
    SIGNAL unnamed_net6 : Std_Logic;
    SIGNAL S2 : Std_Logic;
    SIGNAL C8 : Std_Logic;
    SIGNAL unnamed_net5 : Std_Logic;
    SIGNAL READ : Std_Logic;
    SIGNAL unnamed_net4 : Std_Logic;
    SIGNAL READY : Std_Logic;
    SIGNAL unnamed_net3 : Std_Logic;
    SIGNAL CE_RAM : Std_Logic;
    SIGNAL unnamed_net2 : Std_Logic;
    SIGNAL WRAD : Std_Logic;
    SIGNAL unnamed_net1 : Std_Logic;
BEGIN
-- Architecture statement part
    G001 : G_2AND
    PORT MAP (
        1 => unnamed_net11,
        2 => unnamed_net3,
        3 => unnamed_net2);

    AC_06 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net27,
        2 => A06);

    AC_07 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net31,
        2 => A07);

    AC_08 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net35,
        2 => A08);

    AC_09 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net29,
        2 => A09);

    AC_10 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net33,
        2 => A10);

    AC_11 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net13,
        2 => A11);

    AC_00 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net30,
        2 => A00);

    AC_01 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net34,
        2 => A01);

    AC_02 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net37,
        2 => A02);

    AC_03 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net28,
        2 => A03);

    AC_04 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net32,
        2 => A04);

    AC_05 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net36,
        2 => A05);

    FB200 : ADDRESSCOUNTER
    PORT MAP (
        1 => unnamed_net14,
        2 => unnamed_net2,
        3 => unnamed_net27,
        4 => unnamed_net28,
        5 => unnamed_net29,
        6 => unnamed_net30,
        7 => unnamed_net31,
        8 => unnamed_net32,
        9 => unnamed_net33,
        10 => unnamed_net34,
        11 => unnamed_net35,
        12 => unnamed_net36,
        13 => unnamed_net13,
        14 => unnamed_net37);

    FB100 : TIMEBASE
    PORT MAP (
        1 => unnamed_net12,
        2 => unnamed_net10,
        3 => unnamed_net26,
        4 => unnamed_net17,
        5 => unnamed_net23,
        6 => unnamed_net20,
        7 => unnamed_net25,
        8 => unnamed_net16,
        9 => unnamed_net22,
        10 => unnamed_net19,
        11 => unnamed_net24,
        12 => unnamed_net15,
        13 => unnamed_net21,
        14 => unnamed_net18);

    TB_06 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net26,
        2 => TB_100us);

    TB_07 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net25,
        2 => TB_200us);

    TB_08 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net24,
        2 => TB_500us);

    TB_09 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net23,
        2 => TB_1ms);

    TB_10 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net22,
        2 => TB_2ms);

    TB_11 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net21,
        2 => TB_5ms);

    TB_00 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net20,
        2 => TB_1us);

    TB_01 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net19,
        2 => TB_2us);

    TB_02 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net18,
        2 => TB_5us);

    TB_03 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net17,
        2 => TB_10us);

    TB_04 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net16,
        2 => TB_20us);

    TB_05 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net15,
        2 => TB_50us);

    G003 : G_INV
    PORT MAP (
        1 => unnamed_net5,
        2 => unnamed_net14);

    G000 : G_INV
    PORT MAP (
        1 => unnamed_net12,
        2 => unnamed_net11);

    G002 : G_INV
    PORT MAP (
        1 => unnamed_net4,
        2 => unnamed_net3);

    CLOCK : G_CLKBUF
    PORT MAP (
        1 => CLK,
        2 => unnamed_net10);

    FF003 : G_JKC
    PORT MAP (
        1 => unnamed_net9,
        2 => unnamed_net8,
        3 => VCC,
        4 => GND,
        5 => unnamed_net5);

    FF002 : G_JKC
    PORT MAP (
        1 => unnamed_net7,
        2 => unnamed_net13,
        3 => VCC,
        4 => GND,
        5 => unnamed_net4);

    FF001 : G_JKC
    PORT MAP (
        1 => unnamed_net1,
        2 => unnamed_net6,
        3 => unnamed_net1,
        4 => GND,
        5 => unnamed_net12);

    FF000 : G_JKC
    PORT MAP (
        1 => VCC,
        2 => unnamed_net10,
        3 => unnamed_net11,
        4 => unnamed_net12,
        5 => unnamed_net1);

    START : G_INPUT
    PORT MAP (
        1 => S1,
        2 => unnamed_net9);

    R3 : G_INPUT
    PORT MAP (
        1 => R3,
        2 => unnamed_net8);

    R2 : G_INPUT
    PORT MAP (
        1 => R2,
        2 => unnamed_net7);

    TIME : G_INPUT
    PORT MAP (
        1 => S2,
        2 => unnamed_net6);

    C8 : G_OUTPUT
    PORT MAP (
        1 => unnamed_net5,
        2 => C8);

    RD : G_OUTPUT
    PORT MAP (
        1 => unnamed_net4,
        2 => READ);

    RDY : G_OUTPUT
    PORT MAP (
        1 => unnamed_net3,
        2 => READY);

    CE : G_OUTPUT
    PORT MAP (
        1 => unnamed_net2,
        2 => CE_RAM);

    WR : G_OUTPUT
    PORT MAP (
        1 => unnamed_net1,
        2 => WRAD);

-- Signal assignment part
END netlist;
