-- Structural VHDL generated by gnetlist
-- Context clause
library IEEE;
use IEEE.Std_Logic_1164.all;
-- Entity declaration

ENTITY not found IS
END not found;


-- Secondary unit
ARCHITECTURE netlist OF not found IS
    COMPONENT G_INV
    END COMPONENT ;

    COMPONENT G_TC
    END COMPONENT ;

    SIGNAL QD : Std_Logic;
    SIGNAL unnamed_net6 : Std_Logic;
    SIGNAL QC : Std_Logic;
    SIGNAL unnamed_net5 : Std_Logic;
    SIGNAL CLK : Std_Logic;
    SIGNAL CLEAR : Std_Logic;
    SIGNAL QB : Std_Logic;
    SIGNAL unnamed_net4 : Std_Logic;
    SIGNAL QA : Std_Logic;
    SIGNAL unnamed_net3 : Std_Logic;
    SIGNAL unnamed_net2 : Std_Logic;
    SIGNAL unnamed_net1 : Std_Logic;
    SIGNAL A : Std_Logic;
BEGIN
-- Architecture statement part
    G205 : G_INV
    PORT MAP (
        1 => QC,
        2 => unnamed_net6);

    G204 : G_INV
    PORT MAP (
        1 => QB,
        2 => unnamed_net5);

    G203 : G_INV
    PORT MAP (
        1 => QA,
        2 => unnamed_net4);

    FF203 : G_TC
    PORT MAP (
        1 => unnamed_net2,
        2 => unnamed_net3,
        3 => unnamed_net6,
        4 => QD);

    FF202 : G_TC
    PORT MAP (
        1 => unnamed_net2,
        2 => unnamed_net3,
        3 => unnamed_net5,
        4 => QC);

    G202 : G_INV
    PORT MAP (
        1 => CLK,
        2 => unnamed_net3);

    G201 : G_INV
    PORT MAP (
        1 => CLEAR,
        2 => unnamed_net2);

    FF201 : G_TC
    PORT MAP (
        1 => unnamed_net2,
        2 => unnamed_net3,
        3 => unnamed_net4,
        4 => QB);

    FF200 : G_TC
    PORT MAP (
        1 => unnamed_net2,
        2 => unnamed_net3,
        3 => unnamed_net1,
        4 => QA);

    G200 : G_INV
    PORT MAP (
        1 => A,
        2 => unnamed_net1);

-- Signal assignment part
END netlist;
