-- Structural VHDL generated by gnetlist
-- Context clause
library IEEE;
use IEEE.Std_Logic_1164.all;
-- Entity declaration

ENTITY not found IS
END not found;


-- Secondary unit
ARCHITECTURE netlist OF not found IS
    COMPONENT G_TC
    END COMPONENT ;

    COMPONENT G_INV
    END COMPONENT ;

    COMPONENT G_2AND
    END COMPONENT ;

    SIGNAL unnamed_net10 : Std_Logic;
    SIGNAL unnamed_net9 : Std_Logic;
    SIGNAL unnamed_net8 : Std_Logic;
    SIGNAL unnamed_net7 : Std_Logic;
    SIGNAL B : Std_Logic;
    SIGNAL unnamed_net6 : Std_Logic;
    SIGNAL unnamed_net5 : Std_Logic;
    SIGNAL QD : Std_Logic;
    SIGNAL unnamed_net4 : Std_Logic;
    SIGNAL QC : Std_Logic;
    SIGNAL CLK : Std_Logic;
    SIGNAL CLEAR : Std_Logic;
    SIGNAL QB : Std_Logic;
    SIGNAL unnamed_net3 : Std_Logic;
    SIGNAL QA : Std_Logic;
    SIGNAL A : Std_Logic;
    SIGNAL unnamed_net2 : Std_Logic;
    SIGNAL unnamed_net1 : Std_Logic;
BEGIN
-- Architecture statement part
    G106 : G_2AND
    PORT MAP (
        1 => B,
        2 => unnamed_net10,
        3 => unnamed_net4);

    G104 : G_2AND
    PORT MAP (
        1 => unnamed_net6,
        2 => unnamed_net7,
        3 => unnamed_net9,
        1 => unnamed_net8,
        2 => unnamed_net9,
        3 => unnamed_net10);

    G102 : G_2AND
    PORT MAP (
        1 => unnamed_net5,
        2 => unnamed_net7,
        3 => unnamed_net8);

    G109 : G_INV
    PORT MAP (
        1 => QD,
        2 => unnamed_net7);

    G105 : G_2AND
    PORT MAP (
        1 => B,
        2 => unnamed_net7,
        3 => unnamed_net3);

    G108 : G_INV
    PORT MAP (
        1 => QC,
        2 => unnamed_net6);

    G107 : G_INV
    PORT MAP (
        1 => QB,
        2 => unnamed_net5);

    FF103 : G_TC
    PORT MAP (
        1 => unnamed_net1,
        2 => unnamed_net2,
        3 => unnamed_net4,
        4 => QD);

    FF102 : G_TC
    PORT MAP (
        1 => unnamed_net1,
        2 => unnamed_net2,
        3 => QB,
        4 => QC);

    G101 : G_INV
    PORT MAP (
        1 => CLK,
        2 => unnamed_net2);

    G100 : G_INV
    PORT MAP (
        1 => CLEAR,
        2 => unnamed_net1);

    FF101 : G_TC
    PORT MAP (
        1 => unnamed_net1,
        2 => unnamed_net2,
        3 => unnamed_net3,
        4 => QB);

    FF100 : G_TC
    PORT MAP (
        1 => unnamed_net1,
        2 => unnamed_net2,
        3 => A,
        4 => QA);

-- Signal assignment part
END netlist;
